[package]
name = "Address"
version = "0.0.0"

[dependencies.AptosStdlib]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-stdlib'

[dependencies.MoveStdlib]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/move-stdlib'